### ISSUE TITLE
Make TTF the default font variant

### ISSUE THREAD

**Issue by ForNeVeR** [rexpan/FiraCode-choco#3]
Hello! Some users (aside from me) [complain](https://github.com/tonsky/FiraCode/issues/693) that the default fonts installed (OTF) look more or less weird across different Windows software.

One known workaround for the issue is to install TTF variants by default; Fira Code maintainer [approves the idea](https://github.com/tonsky/FiraCode/issues/693#issuecomment-450578385).

Could we enable TTF by default in this package? Will it properly update for our users then?

Or should we create another package for backwards compatibility?

Thanks!

**Comment by rexpan** [comment]
Created new package https://chocolatey.org/packages/FiraCode-ttf
The reason I create a separate package instead of config parameter is allow user to easily upgrade via `choco upgrade all`.

**Comment by ForNeVeR** [comment]
Thanks! I'll update Fira Code documentation to point to the TTF package as the default.

**Comment by ForNeVeR** [comment]
Just a note: it looks like a package reviewer from chocolatey [requires your answer](https://chocolatey.org/packages/FiraCode-Ttf). Could you contact them, please? Thanks!
