### ISSUE TITLE
Use TTF instead of OTF

### ISSUE THREAD

**Issue by tonsky** [rexpan/FiraCode-choco#5]
OTF should not be used on Windows at all. From v5 Fira Code does not distribute OTF files at all, in any shape or form. As this package has the default name, it would be great if it container TTFs, not OTFs. I’m aware of firacode-ttf but it’s far less popular and hard to find.

If switching to TTF is impossible, this package should be archived, as there will be no new Fira Code versions distributed in OTF.

Thanks!

**Comment by rexpan** [comment]
`Firacode` package will instead TTF from version 5.
`Firacode-ttf` has been deprecated.
