### ISSUE TITLE
Error "The type name 'FontResource.AddRemoveFonts' already exists"

### ISSUE THREAD

**Issue by flcdrg** [rexpan/FiraCode-choco#7]
Trying to install this package after installing another font package (using Boxstarter).

 I think this would be mitigated if this package switched to using https://community.chocolatey.org/packages/chocolatey-font-helpers.extension as that already contains checks to not try and re-register types.

**Comment by rexpan** [comment]
Update and publish to https://community.chocolatey.org/packages/FiraCode/5.2.20210831

**Comment by flcdrg** [comment]
Thanks for the quick response, and extra points for using the `-Multiple` option 😃
